# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('salario', models.DecimalField(decimal_places=2, default=800, max_digits=5, verbose_name='Salário')),
                ('horario_entrada', models.TimeField(verbose_name='Horário de Entrada')),
                ('horario_saida', models.TimeField(verbose_name='Horário de Saída')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('dataCadastro', models.DateField(auto_now_add=True, verbose_name='Data Cadastro')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=16, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
                'verbose_name': 'Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
            ],
            options={
                'verbose_name_plural': 'funcionários',
                'ordering': ['nome'],
                'verbose_name': 'funcionário',
            },
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço')),
                ('codBarra', models.CharField(max_length=50, verbose_name='Código de Barras')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
            ],
            options={
                'verbose_name_plural': 'produtos',
                'ordering': ['descricao'],
                'verbose_name': 'produto',
            },
        ),
        migrations.CreateModel(
            name='produto_Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name_plural': 'Produtos Venda',
                'ordering': ['produto'],
                'verbose_name': 'Produto Venda',
            },
        ),
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venda', models.IntegerField(verbose_name='Número da Venda')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data da Venda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clientes', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario', verbose_name='Vendedor')),
            ],
            options={
                'ordering': ['numero_venda'],
                'verbose_name': 'Venda',
            },
        ),
        migrations.AddField(
            model_name='produto_venda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda', verbose_name='Número da Venda'),
        ),
    ]
