# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('salario', models.DecimalField(decimal_places=2, default=800, max_digits=5)),
                ('horario_entrada', models.IntegerField()),
                ('horario_saida', models.IntegerField()),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('endereco', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('dataCadastro', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('codBarra', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor')),
            ],
            options={
                'ordering': ['descricao'],
                'verbose_name': 'produto',
            },
        ),
        migrations.CreateModel(
            name='produto_Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'ordering': ['produto'],
                'verbose_name': 'Produto Venda',
            },
        ),
        migrations.CreateModel(
            name='venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venda', models.CharField(max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['numero_venda'],
                'verbose_name': 'Venda',
            },
        ),
        migrations.AddField(
            model_name='produto_venda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda'),
        ),
    ]
