# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtd_estoque',
            field=models.IntegerField(default=0, verbose_name='Estoque de Entrada'),
        ),
    ]
