# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ManyToManyField(to='core.funcionario'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ManyToManyField(to='core.clientes'),
        ),
    ]
