# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161121_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='produto',
        ),
        migrations.DeleteModel(
            name='estoque',
        ),
    ]
